# Generated by Django 5.0.14 on 2026-04-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='token',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
