# Generated by Django 5.0.14 on 2026-01-16 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_covers/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='currency',
            field=models.CharField(default='TJS', max_length=3),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, help_text='Public description for website'),
        ),
        migrations.AddField(
            model_name='branch',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='timezone',
            field=models.CharField(default='Asia/Dushanbe', max_length=50),
        ),
        migrations.CreateModel(
            name='BranchWorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(default='09:00')),
                ('close_time', models.TimeField(default='22:00')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.branch')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('branch', 'day')},
            },
        ),
    ]
