# Generated by Django 5.0.14 on 2026-04-04 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_branch_cover_image_branch_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='users.branch')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('branch', 'number')},
            },
        ),
    ]
