# Generated by Django 5.0.14 on 2026-04-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('rect', 'Rectangle'), ('round', 'Round'), ('square', 'Square')], default='rect', max_length=10),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.FloatField(default=9.0),
        ),
    ]
