upstream restaurant_api {
    server web:8000;
}

server {
    listen 80;

    # Сюда приходят запросы за статикой (CSS админки)
    location /static/ {
        alias /app/staticfiles/;
    }

    # Сюда приходят запросы за картинками блюд
    location /media/ {
        alias /app/media/;
    }

    # Все остальные запросы отправляем в Django (Gunicorn)
    location / {
        proxy_pass http://restaurant_api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}