# Generated by Django 5.0.14 on 2026-01-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='catalog.menuitem'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('slug', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='branchmenuitem',
            unique_together={('branch', 'item')},
        ),
    ]
